version: '3.1'
services:
  db:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    links:
      - db

  api:
    image: shopping-cart-api
    build: .
    container_name: shopping-cart-api
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      DB_PORT: ${DB_PORT}
      DB_HOST: db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app